@echo off
REM ======================================================================
REM  ServerManagement+ Smart Start Script (Windows)
REM  Automatically generated by ServerManagement+
REM ======================================================================

:loop
echo [ServerManagement+] Starting Server...

REM --- Extracted Server Launch Command ---
java -Xmx4G -jar server.jar nogui -Dservermanagement.smartstart=true
REM ---------------------------------------

echo [ServerManagement+] Server stopped. Checking for updates...

if exist "update_in_progress.flag" (
    echo [ServerManagement+] Update detected! Waiting for updater to finish...
    
    :wait_update
    if exist "update_finished.flag" (
        echo [ServerManagement+] Update finished! Restarting the server now...
        del "update_in_progress.flag"
        del "update_finished.flag"
        goto loop
    )
    
    timeout /t 1 /nobreak >nul
    goto wait_update
)

echo [ServerManagement+] Normal shutdown detected. Exiting.
