#!/bin/bash
# ======================================================================
#  ServerManagement+ Smart Start Script (Linux)
#  Automatically generated by ServerManagement+
# ======================================================================

while true; do
    echo "[ServerManagement+] Starting Server..."
    
    # --- Extracted Server Launch Command ---
    java -Xmx4G -jar server.jar nogui -Dservermanagement.smartstart=true
    # ---------------------------------------
    
    echo "[ServerManagement+] Server stopped. Checking for updates..."
    
    if [ -f "update_in_progress.flag" ]; then
        echo "[ServerManagement+] Update detected! Waiting for updater to finish..."
        
        while true; do
            if [ -f "update_finished.flag" ]; then
                echo "[ServerManagement+] Update finished! Restarting the server now..."
                rm "update_in_progress.flag"
                rm "update_finished.flag"
                break
            fi
            sleep 1
        done
    else
        echo "[ServerManagement+] Normal shutdown detected. Exiting."
        exit 0
    fi
done
